### ISSUE TITLE
Y Coordinate wrong

### ISSUE THREAD

**Issue by wmarchewka** [krupis/T-Display-S3-esp-idf#1]
The Y coordinate seems backward.  If the USB connector is on the right, the x goes to about 310 or so, but the Y is reversed.  
This is observed in the bsp_touchpad_read() routine.
I cannot see where to change to get this working correctly.  Any idea?

**Comment by krupis** [comment]
@wmarchewka  I am not fully understanding your issue but I assume you want to change the orientation of the display (rotate it 180 degrees). The default orientation of this example is when the USB connector is on the left.

If you want to rotate the display 180 degrees, you need to enable the ```sw_rotate``` for ```disp_drv``` as following:
```
    ESP_LOGI(TAG, "Register display driver to LVGL");
    lv_disp_drv_init(&disp_drv);
    disp_drv.hor_res = EXAMPLE_LCD_H_RES;
    disp_drv.ver_res = EXAMPLE_LCD_V_RES;
    disp_drv.flush_cb = example_lvgl_flush_cb;
    disp_drv.draw_buf = &disp_buf;
    disp_drv.user_data = panel_handle;
    disp_drv.sw_rotate = 1;
    lv_disp_t *disp = lv_disp_drv_register(&disp_drv);
```

Now you can rotate the display using the LVGL function ```lv_disp_set_rotation``` for example:

```
void display_dropdown(){
    lv_disp_t *dispp = lv_disp_get_default();
    ui_Dropdown2 = lv_dropdown_create(lv_scr_act());
        lv_dropdown_set_options(ui_Dropdown2, "Apple\n"
            "Banana\n"
            "Orange\n"
            "Melon\n"
            "Grape\n"
            "Raspberry");
    lv_obj_set_width(ui_Dropdown2, 150);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 0);
    lv_obj_set_y(ui_Dropdown2, -20);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_disp_set_rotation(dispp, LV_DISP_ROT_180);
    lv_obj_add_event_cb(ui_Dropdown2, dropdown_event_handler, LV_EVENT_ALL, NULL);
}
```

Now, the display has been rotated 180 degrees, and the X,Y zero point is bottom left corner of the display:
![image](https://github.com/krupis/T-Display-S3-esp-idf/assets/22237034/2fc132a1-26f2-404a-9a98-d5555b893e44)



I have updated ```master``` branch to include the example for the ```display_dropdown``` that is rotated 180 degrees

Please clarify to me if that answers your question. If not, I will try to provide more information.

**Comment by wmarchewka** [comment]
Thank you for your reply.  I wasn't clear with the specific question i was asking. The red is what i have, the blue is what i was expecting.  If i add a slider to this orientation, the slider does not work as expected.  The X axis is backward.

![IMG_1983](https://github.com/krupis/T-Display-S3-esp-idf/assets/5186401/5d9660d8-8a12-4c18-9433-b79c2abfbb87)

**Comment by krupis** [comment]
@wmarchewka 
I understand what you are talking about right now.

Please try to play around with:
```
esp_lcd_panel_mirror(panel_handle, false, true);
```

try to set the x axis mirroring:
```
esp_lcd_panel_mirror(panel_handle, true, true);
```

or:
```
esp_lcd_panel_mirror(panel_handle, true, false);
```


If that does not work for you, I can look into this a little more tommorow as I currently do not have a spare T-Display-S3 device.

**Comment by krupis** [comment]
@wmarchewka Please have a look at the above ticket. I think your issue has been solved :)

**Comment by wmarchewka** [comment]
That did it.  Odd that once you flag .swap_xy that you have to actually swap the values in x and y. LOL.   Thanks for getting the code together to get me started on this unit and following through with the issue for me.
