### ISSUE TITLE
Touch is disabled in the code.

### ISSUE THREAD

**Issue by davidthings** [krupis/T-Display-S3-esp-idf#2]
Thank you for this lovely example.  I wrestled with the official code for many hours, trying to understand, and not really getting too far.   Then I found this repo and a) the code is well thought out and b) I got good stuff on screen in minutes.  Thanks!!

Meanwhile, a very minor thing: four months ago you checked this in:

``` C
//Change this to 0 if you do not wish to use Touch.
#define USE_TOUCH_DISPLAY 0
```
Made me a little worried when the touch screen wasn't working... 

(-:,

**Comment by krupis** [comment]
> Thank you for this lovely example. I wrestled with the official code for many hours, trying to understand, and not really getting too far. Then I found this repo and a) the code is well thought out and b) I got good stuff on screen in minutes. Thanks!!
> 
> Meanwhile, a very minor thing: four months ago you checked this in:
> 
> ```c
> //Change this to 0 if you do not wish to use Touch.
> #define USE_TOUCH_DISPLAY 0
> ```
> 
> Made me a little worried when the touch screen wasn't working...
> 
> (-:,

Glad it is useful :) 

Regarding USE_TOUCH_DISPLAY I wanted to make sure you can use this code with other variants ( non touch ) of the boards without getting tons of warning or crashes which may happen if you run this on a display without touch hence this flag.
